version: 2.1

jobs:
  test:
    docker:
      - image: circleci/ruby:3.1.7
        environment:
          BUNDLE_JOBS: 4
          BUNDLE_RETRY: 3
          PGHOST: 127.0.0.1
          PGUSER: circleci
          PGPASSWORD: ""

      - image: circleci/postgres:12-alpine
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: app_test
          POSTGRES_PASSWORD: ""

    steps:
      - checkout

      - setup_remote_docker:
          version: 20.10.7

      - run:
          name: Docker Login
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      # Cache gems based on Gemfile.lock
      - restore_cache:
          keys:
            - v1-gems-{{ checksum "Gemfile.lock" }}
            - v1-gems-

      - run:
          name: Install Dependencies
          command: bundle install --jobs=4 --retry=3 --path=vendor/bundle

      - save_cache:
          paths:
            - vendor/bundle
          key: v1-gems-{{ checksum "Gemfile.lock" }}

      # Database setup
      - run:
          name: Prepare Database
          command: |
            cp config/database.yml.ci config/database.yml
            bundle exec rake db:create db:schema:load

      # Run tests
      - run:
          name: Run Tests
          command: bundle exec rspec

workflows:
  version: 2
  test:
    jobs:
      - test
