version: 2.1

orbs:
  ruby: circleci/ruby@1.8.0

executors:
  ruby:
    docker:
      - image: cimg/ruby:3.2.2
  rails:
    docker:
      - image: cimg/ruby:3.2.2
        environment:
          PGHOST: 127.0.0.1
          PGUSER: postgres
          RAILS_ENV: test
      - image: cimg/postgres:14.2
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: ramas_test
          POSTGRES_PASSWORD: postgres

jobs:
  linter:
    executor: ruby
    steps:
      - checkout
      - ruby/install-deps:
          key: gems-v2
  tests:
    executor: rails
    environment:
      BUNDLE_PATH: vendor/bundle
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres:postgres@127.0.0.1
    steps:
      - checkout
      - ruby/install-deps:
          key: gems-v2
      - run:
          name: Load Environment Variables
          command: |
            if [ -f .env.test ]; then
              export $(grep -v '^#' .env.test | xargs);
            fi
      - run:
          command: 'dockerize -wait tcp://localhost:5432 -timeout 1m'
          name: Wait for Postgres
      - run:
          command: 'bundle exec rails db:schema:load --trace'
          name: Database setup
      - ruby/rspec-test

workflows:
  version: 2.1
  linter-and-tests:
    jobs:
      - linter
      - tests
